// This file was automatically generated by 'scritps/antlr/generate_tokens.rb'
grammar mysql_identifiers;

import mysql_tokens;

literal:
    NULL
    | bool_literal
    | float_literal
    | integer_literal
    | string_literal
    | datetime_literal
    ;

identifier: ID | BQUOTED_STRING;
bool_literal: TRUE | FALSE;
float_literal: FLOAT_NUMBER;
integer_literal: INT_NUMBER;
string_literal: SQUOTED_STRING | DQUOTED_STRING;
datetime_literal: CURRENT_DATE | CURRENT_TIME | CURRENT_TIMESTAMP;
